---
- hosts: dev
  become: true
  tasks:
    - name: Install python pip
      apt:
        name: python-pip
        state: present

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: Start the container
      docker_container:
        name: app
        image: lararoft19/app
        state: started
        published_ports:
          - "8080:8080"
